[Base]
; Light green on Dark Blue background
main_fg                               = 7A5CCC
secondary_fg                          = ECF0C1
main_bg                               = 0F111B
sidebar_and_player_bg                 = 0F111B
over_overlay_and_shadow               = 000000
indicator_fg_and_button_bg            = 7A5CCC
pressing_fg                           = B3A1E6
slider_bg                             = 16172D
sidebar_indicator_and_hover_button_bg = 5CCC96
scrollbar_fg_and_selected_row_bg      = 1B1C36
pressing_button_fg                    = ECF0C1
pressing_button_bg                    = 1B1C36
selected_button                       = 5CCC96
miscellaneous_bg                      = 16172D
miscellaneous_hover_bg                = 1B1C36
preserve_1                            = FFFFFF

