# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/wallpapers/garuda-wallpapers/garuda-wp-dessert-01.png'

# Special
background='#0f111b'
foreground='#ecf0c1'
cursor='#ECF0C1'
# Colors
color0='#000000'
color1='#E33400'
color2='#5CCC96'
color3='#B3A1E6' 
color4='#00A3CC'
color5='#F2CE00'
color6='#7A5CCC'
color7='#686F9A'
color8='#686F9A'
color9='#E33400' 
color10='#5CCC96' 
color11='#B3A1E6'
color12='#00A3CC'
color13='#f2CE00'
color14='#7A5CCC'
color15='#F0F1CE'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
